const data = [
  {
    _id: "657bf013308ffa04d2a7c6a5",
    index: 0,
    guid: "f90be19e-bd3f-41fc-b8df-6167e0c1ada2",
    isActive: false,
    balance: "$1,152.37",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "blue",
    name: "Fran Compton",
    gender: "female",
    company: "APEXTRI",
    email: "francompton@apextri.com",
    phone: "+1 (849) 508-3806",
    address: "576 Nolans Lane, Dale, Northern Mariana Islands, 7519",
    about:
      "Anim in esse Lorem quis ullamco. In officia pariatur Lorem duis minim eiusmod pariatur velit est eu aute velit elit Lorem. In pariatur laboris incididunt dolore laboris aliqua enim enim. Deserunt dolore labore duis deserunt cupidatat fugiat officia anim aliquip non. Dolore anim laboris do aliqua esse nostrud.\r\n",
    registered: "2022-11-27T01:07:05 -06:-30",
    latitude: -2.328477,
    longitude: -68.034561,
    tags: ["irure", "dolore", "officia", "culpa", "mollit", "enim", "labore"],
    friends: [
      {
        id: 0,
        name: "Sykes Turner",
      },
      {
        id: 1,
        name: "Flores Horne",
      },
      {
        id: 2,
        name: "Denise Keller",
      },
    ],
    greeting: "Hello, Fran Compton! You have 6 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "657bf0138e9ca9ae74ff64d8",
    index: 1,
    guid: "ea954a65-b605-4966-b2ca-ae9a99409a62",
    isActive: false,
    balance: "$2,680.48",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "brown",
    name: "Herring Bishop",
    gender: "male",
    company: "RODEOCEAN",
    email: "herringbishop@rodeocean.com",
    phone: "+1 (811) 585-2915",
    address: "196 Dodworth Street, Leola, Minnesota, 7597",
    about:
      "Tempor in velit officia dolore Lorem tempor. Aliqua elit incididunt adipisicing voluptate incididunt. Sint officia sunt voluptate officia velit minim pariatur consequat culpa irure aute. Laboris reprehenderit reprehenderit laborum cillum ad do irure proident veniam ad esse.\r\n",
    registered: "2020-02-11T11:53:00 -06:-30",
    latitude: 89.992667,
    longitude: -125.340475,
    tags: ["commodo", "aute", "do", "sunt", "eu", "enim", "do"],
    friends: [
      {
        id: 0,
        name: "Gay Wong",
      },
      {
        id: 1,
        name: "Mccarthy Houston",
      },
      {
        id: 2,
        name: "Hess Wilcox",
      },
    ],
    greeting: "Hello, Herring Bishop! You have 1 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "657bf013d175edee5d535521",
    index: 2,
    guid: "69c61c66-ad83-410b-b779-45337f703bbb",
    isActive: false,
    balance: "$1,590.13",
    picture: "http://placehold.it/32x32",
    age: 27,
    eyeColor: "blue",
    name: "Mildred Richards",
    gender: "female",
    company: "RODEOMAD",
    email: "mildredrichards@rodeomad.com",
    phone: "+1 (803) 533-3484",
    address: "553 Herkimer Place, Dunbar, Arkansas, 5823",
    about:
      "Tempor Lorem laborum dolore ad ad amet ex aute adipisicing excepteur nisi pariatur enim. Officia magna ipsum id sint. Culpa cupidatat dolor in tempor veniam ea consectetur enim est minim deserunt. Dolor laborum nisi duis ea cillum. Ut reprehenderit voluptate proident ad elit amet. Reprehenderit nisi est anim eiusmod non nostrud exercitation laboris esse reprehenderit.\r\n",
    registered: "2016-05-05T02:29:57 -06:-30",
    latitude: 20.32137,
    longitude: -64.484084,
    tags: ["eu", "eu", "nostrud", "veniam", "duis", "nulla", "cupidatat"],
    friends: [
      {
        id: 0,
        name: "Kaitlin Cleveland",
      },
      {
        id: 1,
        name: "Jenifer Pope",
      },
      {
        id: 2,
        name: "Cheri Bruce",
      },
    ],
    greeting: "Hello, Mildred Richards! You have 7 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "657bf013e3a08697d5f319da",
    index: 3,
    guid: "2bc45ee2-e35d-4e76-9fa1-4350e460535c",
    isActive: true,
    balance: "$3,255.47",
    picture: "http://placehold.it/32x32",
    age: 24,
    eyeColor: "green",
    name: "Alejandra Oneil",
    gender: "female",
    company: "KYAGURU",
    email: "alejandraoneil@kyaguru.com",
    phone: "+1 (977) 440-3139",
    address: "811 Hemlock Street, Murillo, Indiana, 6632",
    about:
      "Nulla proident nostrud dolore elit labore. Occaecat eu occaecat et proident incididunt. Occaecat mollit dolore sunt incididunt mollit ut id deserunt in mollit est. Irure occaecat proident labore fugiat ad. Aute commodo non magna aliqua ullamco magna officia veniam commodo nostrud anim. Amet nostrud velit incididunt ad deserunt cupidatat fugiat qui voluptate magna incididunt dolor dolor ad. Officia enim ex mollit nisi ullamco.\r\n",
    registered: "2016-03-26T04:33:10 -06:-30",
    latitude: -2.576259,
    longitude: 159.631207,
    tags: ["in", "proident", "cupidatat", "officia", "adipisicing", "do", "do"],
    friends: [
      {
        id: 0,
        name: "Orr Randolph",
      },
      {
        id: 1,
        name: "Jacobson Shaffer",
      },
      {
        id: 2,
        name: "Ebony Medina",
      },
    ],
    greeting: "Hello, Alejandra Oneil! You have 3 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "657bf01382b93ca8b9d8707a",
    index: 4,
    guid: "8378c5b6-43c4-4594-8add-32193e5a656a",
    isActive: true,
    balance: "$2,819.80",
    picture: "http://placehold.it/32x32",
    age: 31,
    eyeColor: "brown",
    name: "Tammi Richmond",
    gender: "female",
    company: "ECRATIC",
    email: "tammirichmond@ecratic.com",
    phone: "+1 (853) 505-3585",
    address: "448 Bragg Street, Robinson, Tennessee, 4551",
    about:
      "Amet minim in minim laborum incididunt aute fugiat ullamco. Eiusmod dolor voluptate voluptate reprehenderit voluptate consectetur occaecat aute. Est occaecat anim ipsum proident dolore commodo adipisicing elit pariatur esse officia qui laboris. Nostrud voluptate minim id consequat Lorem Lorem eiusmod Lorem in duis. Velit magna ea ad incididunt Lorem ex occaecat amet ex Lorem nulla excepteur.\r\n",
    registered: "2019-05-24T02:46:03 -06:-30",
    latitude: -35.772758,
    longitude: -65.350174,
    tags: [
      "deserunt",
      "mollit",
      "deserunt",
      "laborum",
      "quis",
      "non",
      "officia",
    ],
    friends: [
      {
        id: 0,
        name: "Burt Paul",
      },
      {
        id: 1,
        name: "Lorene Slater",
      },
      {
        id: 2,
        name: "Barrett Molina",
      },
    ],
    greeting: "Hello, Tammi Richmond! You have 10 unread messages.",
    favoriteFruit: "strawberry",
  },
];

const friendsOfAll = data?.filter((item) => item?.gender == "female");
console.log({ friendsOfAll });
